### PR TITLE
Updated base image, require api key

### PR DESCRIPTION
**Pull request by bendangelo**

### CODE REVIEW

**Review by shawnrushefsky — CHANGES_REQUESTED** [review]
I'm good with most of these changes, but I don't want to handle auth in this application.

**Comment by bendangelo** [comment]
That can be taken out.

**Comment by bendangelo** [comment]
Made the changes.

**Review by shawnrushefsky — APPROVED** [review]

**Comment by shawnrushefsky** [comment]
thanks!

**Pull request merged**
